### ISSUE TITLE
tools: loud-fail recorder guard for sdlc-tool verdict record / stage-marker (deferred from #1731)

### ISSUE THREAD

**Issue by tomcounsell** [tomcounsell/ai#1734]
## Context

Issue #1731 fixed the skill-side `$ISSUE_NUMBER` assignment bug (forked stage skills now assign + quote `ISSUE_NUMBER` before recorder calls). As part of that fix, a deferred recorder-level guard was discussed and explicitly NOT built (Q1 = DEFER).

This issue tracks the deferred loud-fail recorder guard.

## What to Build

In `tools/sdlc_verdict.py` and `tools/sdlc_stage_marker.py`, add a guard that exits non-zero when the recording session cannot be verified to OWN the artifact being recorded.

## Critical Constraint

The guard MUST gate on the recording session's **ownership of the artifact**, NOT on a bare `None`/missing `--issue-number`.

**Why this matters**: Many legitimate callers intentionally omit `--issue-number` and rely on `VALOR_SESSION_ID` env resolution (e.g. bridge PM sessions). A naive `if issue_number is None: raise` guard would fire for every such legitimate call.

The correct check is: "if an issue_number was provided AND the resolved session does not own that issue's tracking record, fail loudly." A missing `--issue-number` with a valid `VALOR_SESSION_ID` should proceed silently as before.

## Related

- #1731 — skill-side fix (parent, ships first)
- #1671 / #1672 / PR #1673 — recorder precedence fix (issue-number beats env, must remain intact)

## Labels

`skills`

**Comment by tomcounsell** [comment]
PR #1736 (fix(sdlc): assign ISSUE_NUMBER unconditionally in fork-skill invocations) ships the skill-side fix that is listed as the prerequisite for this issue (`#1731 — skill-side fix (parent, ships first)`).

After #1736 merges, the recorder will always receive an explicitly-passed `--issue-number` from forked skills. At that point, the ownership guard described here becomes meaningful to implement: the recorder can check whether the resolved session owns the issue number it was handed, and exit non-zero if not, without risking false positives on legitimate bridge PM calls that omit `--issue-number` entirely.

The critical constraint noted in this issue (ownership gate, not bare None-guard) remains unchanged — #1736 does not implement any recorder-level guard, only the skill-side assignment.

**Comment by valorengels** [comment]
Duplicate of #1735 — identical scope (deferred loud-fail recorder guard from #1731). Consolidated into #1735, which carries the sharper acceptance criteria and the #1673-precedence-preservation constraint folded in from here. Track the work there.
