### ISSUE TITLE
apply_defaults silently drops the embedding provider when models.memory is imported before agent

### ISSUE THREAD

**Issue by tomcounsell** [tomcounsell/ai#3310]
**Plan:** https://github.com/tomcounsell/ai/blob/main/docs/plans/apply-defaults-embedding-provider-import-cycle.md

## Problem

`config/memory_defaults.py::apply_defaults()` configures the embedding provider inside a bare `except Exception: pass`. When `models.memory` is the first thing imported in a fresh process, the inner `from agent.embedding_provider import configure_embedding_provider` triggers `agent/__init__.py`, which eagerly imports `agent.agent_session_queue` and, through it, the half-initialized `models.memory`. The resulting `ImportError` is swallowed and `get_default_provider()` returns `None` for the life of the process.

Controlled comparison on main (`06ccc8d50`):

```
.venv/bin/python -c "import agent, models.memory; from popoto.fields.embedding_field import get_default_provider; print(get_default_provider())"
# -> <popoto.embeddings.openai.OpenAIProvider ...>

.venv/bin/python -c "import models.memory; from popoto.fields.embedding_field import get_default_provider; print(get_default_provider())"
# -> None
```

## Consequences

- Any entrypoint whose first import is `models.memory` ranks memory by BM25 only, with no query-embedding signal, and nothing logs it.
- Two workarounds already exist in the tree and neither fixes the cause: `scripts/spike/hybrid_retrieval_spikes.py` imports `agent` first and re-runs `configure_embedding_provider()`; `tools/memory_eval/provider_gate.py` refuses to rely on the implicit provider at all.
- Surfaced again by lane 4 (#3216, PR #3309): the evaluation arms inherit whichever provider the parent's import order happened to produce.

## Fix shape

Break the cycle rather than papering over it: `agent/embedding_provider.py` has no `agent` package dependencies (its imports are `logging`, `os`, `pathlib`), so `apply_defaults` can reach it without triggering `agent/__init__`, or the provider configuration can move out of `apply_defaults` into an explicit call at the process entrypoints. Either way, replace `except Exception: pass` with a logged failure so a missing provider is visible. Add a test that imports `models.memory` first in a subprocess and asserts a provider is configured.

Refs #3177 (found during lane 4, #3216).

---

## Triage 2026-09-15

**Status:** confirmed — reproduced on main (205344717). `python -c "import models.memory; from popoto.fields.embedding_field import get_default_provider; print(get_default_provider())"` prints `None`. Root cause traced with a loud (non-swallowing) `apply_defaults`: `models/memory.py:24` → `apply_defaults()` → `config/memory_defaults.py:249` imports `agent.embedding_provider` → triggers `agent/__init__.py` → `agent_session_queue` → `session_executor` → `agent/session_health.py:43` (`from models.memory import Memory`) → `ImportError: cannot import name 'Memory' from partially initialized module 'models.memory'`, caught and dropped by `config/memory_defaults.py:252` (`except Exception: pass`).

**Single-line hotfix:** No. Narrowing `except Exception` to `except ImportError` at `config/memory_defaults.py:252` changes nothing — the swallowed exception already is an `ImportError`. The real fix is breaking the cycle so `agent.session_health` doesn't reach back into `models.memory` at module-import time (or so `agent/__init__.py` doesn't eagerly pull in `agent_session_queue` → `session_executor` → `session_health` just to expose `configure_embedding_provider`), which is a multi-file change, not a one-liner.

**Reduce-complexity option:** Partially. The bare `try/except Exception: pass` around the embedding-provider call is exactly the "happy path + Sentry" anti-pattern — it converts a real import-order bug into permanent, silent, process-lifetime degradation with zero signal. Recommend removing that specific try/except (let a genuine `ImportError` here raise/log loudly to Sentry) while keeping the *intentional* degradation path inside `configure_embedding_provider()` itself (missing `OPENAI_API_KEY` is legitimately optional and already logs a warning). That alone doesn't fix the underlying circular import, but it converts a silent multi-day failure mode into an immediate, loud one.

---

## Recon Summary

**Confirmed:** 4 items — ready to include
- Cycle chain verified in tree: `models/memory.py:24` calls `apply_defaults()` at import time; `config/memory_defaults.py:249` does `from agent.embedding_provider import ...` which executes `agent/__init__.py` (eager `agent_session_queue` import); `agent/session_health.py:43` does `from models.memory import Memory`, closing the loop on a half-initialized module.
- Swallow site verified: `config/memory_defaults.py:252-253` is `except Exception: pass`, so the resulting `ImportError` leaves `get_default_provider()` returning `None` for process lifetime with zero log signal.
- Provider module is cycle-free: `agent/embedding_provider.py` imports only `logging`, `os`, `pathlib` (+ lazy `dotenv`/`popoto` inside the function), so reaching it without triggering `agent/__init__` is feasible.
- Workarounds exist and neither fixes the cause: `scripts/spike/hybrid_retrieval_spikes.py:20-25` imports `agent` first and re-runs `configure_embedding_provider()`; `tools/memory_eval/provider_gate.py` refuses to rely on the implicit provider.

**Revised:** 1 item — scope adjusted
- Fix shape narrowed to two candidate cuts (import-by-path reaching `agent.embedding_provider` without executing `agent/__init__`, vs explicit provider setup at process entrypoints), plus replacing the bare `except` with a logged failure; entrypoint inventory (`bridge/` startup vs worker/CLI paths that import `models.memory` first) happens during planning.

**Pre-requisites:** 0 items — none. No blocker; the triage reproduction on main stands.

**Dropped:** 1 item — removed from scope
- Narrowing `except Exception` to `except ImportError`: the swallowed exception already is an `ImportError`, so the narrowing changes nothing (per issue triage). Dropped as a fix; logging loudly is kept.
