### ISSUE TITLE
Step 2 (blocked on #3001): upgrade anthropic to 1.x + pydantic-ai-slim to 2.33.0+, behind the compat gate

### ISSUE THREAD

**Issue by valorengels** [tomcounsell/ai#3073]
> **Context:** This repo makes every non-harness LLM call through [PydanticAI](https://ai.pydantic.dev/) wrapped by [`agent/llm/wrapper.py`](agent/llm/wrapper.py)'s `run_typed`, which reaches the Anthropic API through the [`anthropic`](https://github.com/anthropics/anthropic-sdk-python) SDK. Both are pinned exactly in [`pyproject.toml`](pyproject.toml) and are currently **25 minor versions stale** because of a stopgap. This issue is **Step 2** of the two-step sequencing the owner agreed in [#3001](https://github.com/tomcounsell/ai/issues/3001) ([comment](https://github.com/tomcounsell/ai/issues/3001#issuecomment-5420111955)): gate first, upgrade second. Step 1 (the compat gate) is #3001's own lane, planned in [`docs/plans/unblock-dependency-bumps-coupled-set-gate.md`](docs/plans/unblock-dependency-bumps-coupled-set-gate.md).

## Blocked on #3001

**This issue must not start until #3001's gate lane has merged.** That sequencing is the entire point of gate-first, and #3001's plan says so explicitly in its Rabbit Holes:

> Do not attempt the upgrade "while we're in here." That is Step 2, behind this gate, in its own lane. A gate landing in the same PR as the bump it gates gives you no way to tell which half is at fault.

Concretely, this lane's **final act** is removing the `hold="#3001 Step 2"` from the `anthropic` + `pydantic-ai-slim` `CoupledSet` that #3001 introduces in `scripts/update/deps.py`. That symbol does not exist until #3001 merges.

## Problem

**Current behavior:**

`pyproject.toml` pins:

```
"anthropic==0.125.0",
"pydantic-ai-slim[anthropic]==2.9.0",   # CRITICAL — pin exact
"openai>=1.0.0",                        # Embedding API for semantic doc impact finder
```

The `anthropic==0.125.0` pin is a **stopgap from `7db5b82bb`** (re-applied by `7a30b88f7` after `d0c02bde5` put the bad pin back), not a decision to stay on 0.x. It exists because anthropic 1.0.0 removed `temperature`/`top_p`/`top_k` from the Messages API while `pydantic-ai-slim==2.9.0` passes all three unconditionally as the `OMIT` sentinel — which still binds the keyword — so every `run_typed` call died at argument binding with `TypeError: AsyncMessages.create() got an unexpected keyword argument 'temperature'`.

The stopgap stops the bleeding and **deliberately leaves us stale**. Nothing here is a forward path.

**Desired outcome:**

The stack runs on a current, genuinely compatible pair — `pydantic-ai-slim>=2.33.0` with `anthropic>=1.0.0` — with a real `run_typed` call succeeding against it, landed behind the gate #3001 builds and with the `hold` removed so routine auto-bumps resume.

## Definitions

| Term | Definition | Reference |
|------|-----------|-----------|
| `run_typed` | The wrapper every non-harness LLM call goes through; runs a PydanticAI agent and validates the response against a Pydantic schema. | [`agent/llm/wrapper.py`](agent/llm/wrapper.py) |
| `CoupledSet` / `hold` | Introduced by #3001: a set of packages that must be bumped atomically. A truthy `hold` makes `auto_bump_deps` skip the set with a legible reason, so re-enrolling `anthropic` in the auto-bump structure does not auto-execute this upgrade on the next cron tick. | `scripts/update/deps.py` (after #3001) |
| Compat gate | #3001's `agent/llm/compat.py::check_llm_stack_compat()` — the run-boundary predicate answering "is the installed LLM stack a pair we can actually call?" | [`docs/plans/unblock-dependency-bumps-coupled-set-gate.md`](docs/plans/unblock-dependency-bumps-coupled-set-gate.md) |
| httpx2 | The HTTP client library anthropic 1.0.0 moved its transport layer onto, replacing `httpx`. | [httpx](https://www.python-httpx.org/) |

## Prior Context

- **#3001** — parent issue. Its lane is Step 1 only (the gate). Its plan's No-Gos list this work as `[SEPARATE-SLUG #3001] The dependency upgrade itself`, and its Verification table carries three **anti-criteria** asserting the pins are *unchanged* by that lane. This issue is where those pins finally move.
- **`9d1488ccb`** — the breaking auto-bump that started all of this; it passed the existing import-only smoke gate cleanly.
- **`7db5b82bb`**, **`7a30b88f7`** — two separate emergency reverts of the same pin, eleven commits apart.
- **`d0c02bde5`** — the stopgap removing `anthropic` from `AUTO_BUMP_PACKAGES`; it also itself re-shipped the bad pin via a hand-staged commit.

## Solution Sketch

**The version boundary is exact and must not be softened.** Per #3001's Research section:

- **`pydantic-ai-slim>=2.33.0` is the first release that genuinely supports `anthropic>=1.0.0`** (the "use httpx2 for Anthropic clients" fix). Every earlier release — **including 2.32.2** — allowed `anthropic 1.0.0` in its metadata *without supporting it*. The upper-bound hole is upstream metadata we do not control, which is why #3001's local check exists at all. Do not treat a clean `uv` resolution as evidence of compatibility; that is precisely what failed on 2026-08-24.

**Two distinct breaking axes in anthropic 1.0.0:**

1. **Argument binding** — `temperature`/`top_p`/`top_k` removed from the Messages API. This is the one that caused the incident; it fails before any network I/O.
2. **Transport** — the HTTP layer moved to `httpx2`, and `AnthropicProvider(http_client=...)` now rejects a legacy `httpx.AsyncClient`. `wrapper.py` constructs `AsyncAnthropic` directly with no custom `http_client`, so it is not exposed to this *today*, but a transport break is a second way `run_typed` can die and is why the gate makes a real call rather than a signature check.

**The `openai` 2.x → 3.x move is a related but separately-motivated bump.** #3001's spike-5 established there is **no packaging coupling**: `pydantic-ai-slim`'s locked dependencies contain no `openai`, and `openai>=3.0.0` is declared only under the `[openai]` extra, which this repo does not install. `openai` is therefore in **no** coupled set, asserted in code. The real coupling was self-inflicted — `wrapper.py`'s module-scope `from pydantic_ai.models.openai import OpenAIChatModel` failed under pydantic-ai 2.34.0 + the pinned openai 2.30.0, taking the Anthropic path down with it — and #3001's import-safety contract fixes that at the import. So this lane should decide the `openai` bump on its own merits, and must exercise the six modules that import `openai` directly (verified present on `main` at time of filing):

- `tools/cross_vendor_judge.py`
- `tools/impact_finder_core.py`
- `tools/image_gen/__init__.py`
- `tools/selfie/__init__.py`
- `tools/tts/__init__.py`
- `tools/knowledge/converter.py`

Note that pydantic-ai's own error text on a too-old `openai` reads "Please install `openai`", which is **misleading** — openai *is* installed, just too old. Do not chase that message.

**Also folded in** (from #3001's No-Gos, deferred here because findings can only be acted on where pins move): audit the remaining `CRITICAL — pin exact` dependencies in `pyproject.toml` for the same staleness, and record the findings.

## Recon Summary

**Confirmed:** 4 items
- The three pins are unchanged on `origin/main` at `b87fb26de`: `anthropic==0.125.0`, `pydantic-ai-slim[anthropic]==2.9.0`, `openai>=1.0.0`.
- The six `openai`-importing modules all exist at the paths listed above (grep-verified).
- #3001's plan explicitly excludes this work and asserts anti-criteria that the pins stay put in that lane.
- The `2.33.0` boundary and the httpx2 transport change are recorded in #3001's Research section with sources.

**Revised:** 1 item
- **The coupling is a pair, not a triple.** #3001's original comment thread called this a three-way coupling (`anthropic` + `pydantic-ai-slim` + `openai`). Spike-5 disproved that: the openai failure was an import-graph artifact of `wrapper.py`, not a packaging constraint. Plan accordingly — `openai` moves for its own reasons, not because the set demands it.

**Pre-requisites:** 1 item
- **#3001 must merge first.** Removing the `hold` is this lane's final act, and the symbol does not exist before then.

**Dropped:** 1 item
- **Pinning `openai` exactly.** #3001's round-2 critique dropped this as scope creep that also masked its own regression test's target. The `>=1.0.0` floor stays unless this lane makes a deliberate, separately-justified decision to change it.

## Acceptance Criteria

- [ ] #3001 is merged before this lane's first code commit (stated in the PR description).
- [ ] `pyproject.toml` pins `pydantic-ai-slim[anthropic]>=2.33.0` (exact pin, per the repo's `CRITICAL — pin exact` convention) and `anthropic>=1.0.0`, with `uv sync --all-extras` resolving cleanly.
- [ ] A real `run_typed` call succeeds against the upgraded stack — a live API call, not a mock. Per this repo's testing philosophy, a mocked check cannot catch an argument-binding break, which is the exact failure mode being guarded.
- [ ] `python -m agent.llm.compat --json` (#3001's predicate) reports `"compatible": true` on the upgraded pair.
- [ ] The `openai` 2.x → 3.x decision is made explicitly and recorded. If taken, all six `openai`-importing modules are exercised against 3.x before the upgrade lands.
- [ ] The `hold="#3001 Step 2"` is removed from the `anthropic` + `pydantic-ai-slim` `CoupledSet` as the lane's final change, and a subsequent `auto_bump_deps` run is observed to evaluate (not skip) the set.
- [ ] Remaining `CRITICAL — pin exact` dependencies are audited for staleness, with findings recorded in the PR description.
- [ ] The two-line `pyproject.toml` comment above the `anthropic` pin still names the coupled-set constraint and still points at `AUTO_BUMP_SETS`; the version boundary it states is updated to match reality.
- [ ] Full test suite green (`/do-test`); docs updated (`/do-docs`).

## Downstream

This issue feeds into `/do-plan`, which will produce a plan document at `docs/plans/{slug}.md`, then executed by `/do-build`.

Constraints for the planner:

- **Do not start before #3001 merges.** If the router reaches this issue while #3001 is unmerged, stop and report rather than planning around it.
- Do not re-litigate the gate design. This lane consumes #3001's gate; it does not modify it.
- Do not touch `models/agent_session.py` or `tests/unit/test_agent_session.py` — that is the sibling Work Item 2 lane.
- The `2.33.0` floor is a hard finding, not an estimate. A resolver that offers `2.32.2` against `anthropic 1.0.0` is offering a combination upstream metadata permits and upstream code does not support.

**Comment by x711criptic** [comment]
If this is about agent tooling — x711 has 26 pay-per-use tools (web search, prices, shared memory, tx simulation) with a free tier. No signup to start, MCP supported.

```bash
curl -X POST https://x711.io/api/refuel \
  -H "Content-Type: application/json" \
  -d '{"tool":"price_feed","query":"ETH"}'
```

_Feel free to ignore if this isn't relevant to what you're working on._

---
**[⚡ x711.io/go](https://x711.io/go?source=gh-issue)** — 7 seconds, no terminal. Free tier, 41 tools, MCP included.

**Comment by tomcounsell** [comment]
Triage 2026-09-04: this is now unblocked. #3001 is closed, its gate lane merged, and the CoupledSet with hold="#3001 Step 2" exists at scripts/update/deps.py:479 (the symbol this lane's final act removes). Ready for a full SDLC lane; it is a coupled dependency bump behind the compat gate and should not be hotfixed.
