### ISSUE TITLE
chore: fix 54 pre-existing test failures on main (6 categories: drift, missing artifact, bugs, env, flaky, perf)

### ISSUE THREAD

**Issue by valorengels** [tomcounsell/ai#1578]
**Plan:** https://github.com/tomcounsell/ai/blob/main/docs/plans/test-suite-cleanup.md

> **Context:** This repo runs a full `pytest` suite of 8,300+ tests on every PR. As of 2026-06-05, `main` has 54 pre-existing test failures and 1 collection error — tests that broke silently as features evolved and were never fixed. Until these are resolved, the test suite cannot serve as a reliable regression gate: any new failure on a PR must be manually checked against this known-bad baseline.

## Problem

Running `scripts/pytest-clean.sh tests/ -v --tb=short` on `main` produces 54 failures and 1 collection error. These are not caused by the current work — they predate recent PRs and represent accumulated drift between source code and tests.

**Current behavior:** 54 tests fail on `main`. Every PR must verify its failures are "pre-existing," which is manual work and easy to get wrong.

**Desired outcome:** `main` passes with 0 failures. Every failure on a PR is a genuine regression introduced by that branch.

## Definitions

| Term | Definition | Reference |
|------|-----------|-----------|
| xdist | pytest-xdist — runs tests in parallel across worker processes; some tests only fail under parallelism (flaky) | [pyproject.toml](pyproject.toml) |
| `scripts/pytest-clean.sh` | Wrapper script that reaps orphan xdist workers on exit to prevent memory leaks | [scripts/pytest-clean.sh](scripts/pytest-clean.sh) |
| reprieve scoping | A mechanism in the session health-check that grants a "free pass" recovery attempt — currently only meant to apply to `no_progress` exit reasons | [agent/session_executor.py](agent/session_executor.py) |
| reflection registry | YAML-driven scheduler that runs named reflection routines on a schedule | [config/reflections.yaml](config/reflections.yaml) |

## Failure Inventory

Classified by root cause after recon.

### A. Feature drift — update tests to match current source (20 failures)

| Cluster | Count | Diagnosis |
|---------|-------|-----------|
| `test_session_modal_liveness_render` | 6 | Template CSS classes / conditional logic changed; tests assert old output |
| `test_bridge_relay::TestSendQueuedMessage` | 5 | `bridge/telegram_relay.py` file-send API changed; tests assert old contract |
| `test_sdlc_skill_md_parity` | 3 | SKILL.md Step 4 heading gained a parenthetical; exact-match regex broke |
| `test_reflection_scheduler` | 4 | `config/reflections.yaml` uses `every: 300s` but tests expect `interval: 300` |
| `test_model_relationships::test_enrichment_field_count` | 1 | `TelegramMessage` grew from 18 to 20 fields; test hardcodes 18 |
| `test_long_task_checkpointing::test_progress_md_in_build_soft_check` | 1 | Test looks for `.claude/skills/do-build/SKILL.md`; canonical path is `.claude/skills-global/do-build/SKILL.md` |

### B. Missing artifact — code referenced by tests not present on `main` (11 failures)

| Cluster | Count | Diagnosis |
|---------|-------|-----------|
| `test_do_merge_review_filter` | 10 | Tests read `.claude/commands/do-merge.md` which exists only in a worktree. Land the feature or delete the tests. |
| `test_markitdown_ingestion` | 1 | `cannot import name 'full_scan' from 'tools.knowledge.indexer'` — function removed or renamed |

### C. Real bugs — source behaviour does not match documented spec (10 failures)

| Cluster | Count | Diagnosis |
|---------|-------|-----------|
| `test_watchdog_recovery::TestWatchdogDetectsUnexpectedExit` | 4 | Watchdog returns `ok` after worker killed; heartbeat TTL too permissive (132s-old heartbeat still healthy) |
| `test_harness_oom_backoff` | 2 | `pre_bump_attempts = entry.recovery_attempts or 0` capture line missing from `session_executor.py`; OOM backoff ordering not implemented |
| `test_health_check_recovery_finalization` | 4 | Reprieve scoping guard (`_reason_kind == "no_progress"`) may be absent — reprieve applied to all recovery types |

### D. Environment / install issues (2 failures)

| Cluster | Count | Diagnosis |
|---------|-------|-----------|
| `test_memory_mcp_server::test_fresh_shell_import_resolution` | 1 | `ModuleNotFoundError: No module named 'mcp'` — add to test requirements or add `skipif` guard |
| `test_skills_audit` (collection error) | 1 | `ModuleNotFoundError: No module named 'audit_skills'` — fix import path in conftest |

### E. Flaky under xdist — passes in isolation (`-n0`), fails in parallel (2 failures)

| Cluster | Count | Diagnosis |
|---------|-------|-----------|
| `test_memory_ingestion::test_human_message_creates_memory` | 1 | Likely Redis key collision between parallel workers |
| `test_compose_system_prompt::test_pm_cell_byte_stable_against_local_fixture` | 1 | Likely shared fixture or non-deterministic ordering under parallelism |

### F. Performance / timing thresholds (6 failures)

| Cluster | Count | Diagnosis |
|---------|-------|-----------|
| `test_memory_prefetch::test_prefetch_completes_under_budget` | 1 | 8.25s actual vs 5s budget |
| `test_benchmarks::TestEndurance::test_garbage_collection` | 1 | GC threshold may need recalibration |
| `test_doc_impact_finder_sdk::TestLiveHaikuReranking` | 4 | Live Haiku API integration tests — latency, missing CI key, or changed response format |

## Solution Sketch

Work through categories in order (A then B–F can be parallelised):

- **A (drift):** Read current source, update test assertions. Do not change source behaviour.
- **B (missing artifact):** For `do-merge.md` — land on `main` or delete 10 tests. For `full_scan` — trace rename and fix import.
- **C (bugs):** Fix source. Watchdog TTL, OOM backoff capture ordering, and reprieve scoping are documented behaviours not yet implemented.
- **D (env):** Add `mcp` to test requirements; fix `audit_skills` conftest import.
- **E (flaky):** Add `@pytest.mark.xdist_group` or use unique Redis key prefixes per worker.
- **F (performance):** Profile slow paths; fix or document revised thresholds with comments.

## Recon Summary

**Confirmed:**
- All 6 categories validated by direct code inspection and targeted test runs (`-n0`).

**Revised:**
- `test_memory_ingestion` and `test_compose_system_prompt` are flaky under parallelism only (confirmed by passing with `-n0`).

**Pre-requisites:**
- `test_do_merge_review_filter` (10 failures) requires a product decision before the fix can proceed: land `do-merge.md` or delete the tests.

**Dropped:**
- None.

## Acceptance Criteria

- [ ] `scripts/pytest-clean.sh tests/ -q` on `main` exits 0 with 0 failures and 0 errors
- [ ] All Category A test files updated to match current source behaviour
- [ ] `test_do_merge_review_filter`: `do-merge.md` merged to `main` OR 10 tests deleted with explanation
- [ ] `full_scan` import resolved so `test_markitdown_ingestion` passes
- [ ] Category C bugs (watchdog TTL, OOM backoff capture, reprieve scoping) fixed in source
- [ ] `mcp` in test requirements and `audit_skills` import resolved
- [ ] Flaky xdist tests isolated with `xdist_group` or unique Redis key prefixes
- [ ] Category F thresholds justified with a comment or slow path fixed

## Downstream

This issue feeds into `/do-plan`, which will produce a plan at `docs/plans/test-suite-cleanup.md`. The plan should batch work by category (A–F) and allow parallel execution across categories that don't share files.

**Constraint:** Do not weaken assertions to make tests pass — fix the source or update the test to match the *intended* current behaviour, not the *accidental* one.
