### ISSUE TITLE
Work Item 2 residue: unmask the append_event TypeError in the worker_key fixture, audit #2949's silent constructor-kwarg drops, decide on rejecting unknown kwargs

### ISSUE THREAD

**Issue by valorengels** [tomcounsell/ai#3074]
> **Context:** `AgentSession` is this repo's Redis-backed session model, stored via [Popoto](https://github.com/tomcounsell/popoto), an ORM whose `Model.__init__` accepts declared `Field`s and **silently ignores unknown kwargs**. PR #2949 (`69dc69568`) converted `stage_states` from a stored Popoto `Field` into a property backed by `session_events`. Test fixtures that passed `stage_states=` to the constructor therefore became silent no-ops, and the #1228 worker-key routing guard went green-but-dead without anyone noticing. This is **Work Item 2** of [#3001](https://github.com/tomcounsell/ai/issues/3001), split out per the owner's confirmation of Open Question 4 in [`docs/plans/unblock-dependency-bumps-coupled-set-gate.md`](docs/plans/unblock-dependency-bumps-coupled-set-gate.md).

## Scope correction, up front

**The headline half of Work Item 2 has already landed.** Commit [`56e80d843`](https://github.com/tomcounsell/ai/commit/56e80d843) ("fix(tests): set stage_states through the setter, not a constructor kwarg", 2026-08-31, `Refs #2852`) migrated `_make_session` onto the setter path and added a fixture self-check. Verified on `origin/main` at `b87fb26de`:

```
$ ./scripts/pytest-clean.sh tests/unit/test_agent_session.py -k "TestWorkerKeyProperty or TestWorkerKeyTruthTable" -q
25 passed in 9.34s
```

That commit landed under a *different* umbrella (#2852, now closed) and was never recorded against #3001, which is why #3001's plan still lists Work Item 2 as outstanding. **This issue is therefore the residue**, not the original ask, and it is smaller than #3001 describes. Do not re-do the fixture migration.

## Problem

**Current behavior:**

Three things the fixture fix did not address remain live on `main`.

**1. The fixture's `save` stub still has the wrong signature, masking a `TypeError` on every construction.** `_make_session` (`tests/unit/test_agent_session.py:154`) installs `AgentSession.save = lambda self: None`. The `stage_states` setter routes through `append_event`, which calls `self.save(update_fields=[...])`. Reproduced against `origin/main`:

```
current_stage= BUILD worker_key= my-feature
WARNING:models.agent_session:append_event save failed for session dbg-sid-1
  (event_type='stage'): <lambda>() got an unexpected keyword argument 'update_fields'
```

The tests pass — the in-memory event still lands — but every stage-setting construction emits a **swallowed `TypeError`**. A restored guard that logs a masked exception on every use is exactly the class of quiet failure this work item exists to end. Fix: widen the stub to `lambda self, **kwargs: None`.

**2. The #2949 audit was never performed.** `stage_states` is the property conversion that happened to surface. `Model.__init__` silently dropping unknown kwargs is a general hazard, and any other call site still passing a now-converted property as a constructor kwarg is silently no-op'ing today with no test to notice.

**3. No decision is recorded on whether `AgentSession.__init__` should reject unknown kwargs.** #3001 names this as the durable fix — "a kwarg that is silently ignored rather than rejected fails quietly everywhere" — and it is still an open question.

**Desired outcome:**

The restored guard runs clean with no masked exception; every other silent constructor-kwarg drop introduced by #2949's property conversions is found or proven absent; and the repo has a recorded decision on rejecting unknown kwargs at construction, so the next property conversion cannot repeat this silently.

## Definitions

| Term | Definition | Reference |
|------|-----------|-----------|
| `worker_key` | Computed property deciding which worker loop a session serializes on. Slugged Eng sessions at worktree stages route by slug so siblings run concurrently; everything else serializes on `project_key`. | [`models/agent_session.py:658-705`](models/agent_session.py#L658-L705) |
| `stage_states` | JSON map of SDLC stage → status. Since #2949 it is a **property** over `session_events`, no longer a stored Popoto Field. | [`models/agent_session.py:1613`](models/agent_session.py#L1613) |
| Popoto | The Redis ORM backing `AgentSession`. Its constructor accepts declared `Field`s and silently ignores unknown kwargs. | [popoto](https://github.com/tomcounsell/popoto) |
| `append_event` | Appends a `SessionEvent` to `session_events` and persists with `save(update_fields=["session_events", "updated_at"])`. Its save failure is caught and logged, never raised. | `models/agent_session.py` |

## Prior Context

- **#1228** — established that sibling Eng sessions route to distinct worker loops; the invariant whose guard went dead.
- **#2949** (`69dc69568`) — the property conversion. Note its removal of the legacy kwarg mapping is **pinned by a test**: `tests/unit/test_agent_session_legacy_surface.py::TestNormalizeKwargsLegacyPathsRemoved::test_legacy_key_does_not_crash_normalization` parametrizes `"stage_states"` among keys that must survive normalization untouched. **Restoring the kwarg mapping is not an available fix** — it would turn that pin red. The motivation is in that module's docstring: the sibling `commit_sha`/`summary` paths were unguarded and grew `session_events` without bound on every hydration.
- **`56e80d843`** — the fixture migration, already merged (see Scope correction).
- **#2971, #2982–#2989** — nine auto-filed duplicates for the nine failing nodes, all closed as duplicates of #3001. Their bodies **misattribute** the failures to the anthropic dependency break; that diagnosis is wrong.
- **#3001** — parent. Its plan's Verification table carries an anti-criterion that its own lane leaves `models/agent_session.py` and `tests/unit/test_agent_session.py` untouched, reserving them for this issue.

## Solution Sketch

- Widen the `_make_session` `save` stub to accept `**kwargs`, and assert no `append_event save failed` warning is emitted during fixture construction — otherwise the same masking returns the next time the stub drifts from the real signature.
- Audit every `AgentSession(...)` construction site (tests and production) for kwargs that are no longer declared `Field`s after #2949's property conversions. Report the finding either way; "audited, none found" is a valid and useful outcome, but it must be stated rather than assumed.
- Decide and record whether `AgentSession.__init__` should reject unknown kwargs. This is a genuine open design question with a real cost on both sides — rejecting is the durable fix, but Popoto's tolerance may be load-bearing for hydration paths, and the #2949 docstring shows unguarded kwarg handling has already caused unbounded `session_events` growth once. `/do-plan` should treat this as a question to investigate, not a direction to execute.

**Worth checking during the audit** (raised in #3001's comments, not yet verified by this filing): the two negative-control tests `test_eng_session_with_slug_at_plan_stage_uses_project_key` and `test_eng_session_with_slug_at_issue_stage_uses_project_key` were passing *vacuously* before `56e80d843` — they assert `worker_key == "test-project"` and got it from `current_stage=None` rather than from the intended PLAN/ISSUE fallback. The new fixture self-check plausibly fixed this as a side effect; confirm rather than assume.

## Recon Summary

**Confirmed:** 3 items — verified directly against `origin/main` at `b87fb26de`
- The 25 worker-key tests pass; the fixture migration is merged.
- The `save`-stub `TypeError` is still emitted and swallowed on every stage-setting construction (reproduced, output above).
- `tests/unit/test_agent_session_legacy_surface.py` pins the removal of the kwarg mapping, foreclosing the shorter-looking fix.

**Revised:** 1 item — scope corrected
- **This is no longer "restore the dead guard".** The guard is restored. Scope is the masked `TypeError`, the audit, and the design decision.

**Dropped:** 2 items — removed from scope
- **"All 9 worker-key tests pass"** as an acceptance criterion — already true, and the count was always an undercount (25 nodes in the two classes).
- **The `SDLC_STAGES` / `PATCH` omission** found during the same triage (`models/agent_session.py:81` omits `PATCH` while `agent/pipeline_state.py:58` includes it, making the `PATCH` entries in `_ENG_WORKTREE_STAGES` and `resolve_branch_for_stage` unreachable). It was filed separately as a live routing defect and should not be re-scoped here.

## Acceptance Criteria

- [ ] `_make_session`'s `save` stub accepts `**kwargs`, and a test asserts no `append_event save failed` warning is logged during fixture construction.
- [ ] The two worker-key test classes still pass (25 nodes), and they still **fail** if `worker_key`'s slug-precedence logic is reverted — i.e. the guard is live, not merely green.
- [ ] Every `AgentSession(...)` construction site is audited for kwargs that are no longer declared `Field`s post-#2949; findings recorded in the PR description, including an explicit "none found" if that is the result.
- [ ] A decision on whether `AgentSession.__init__` should reject unknown kwargs is **recorded** (in the plan doc and, if the answer is yes, implemented with tests). A recorded "no, and here is why" closes this criterion.
- [ ] The PLAN/ISSUE negative controls are confirmed non-vacuous, or made so.
- [ ] `tests/unit/test_agent_session_legacy_surface.py` still passes — the kwarg mapping stays removed.
- [ ] Tests pass (`/do-test`); docs updated if the kwarg-rejection decision changes model behavior (`/do-docs`).

## Downstream

This issue feeds into `/do-plan`, which will produce a plan document at `docs/plans/{slug}.md`, then executed by `/do-build`.

Constraints for the planner:

- **This is not a production incident.** #3001 verified that the only non-test `stage_states=` call sites (`agent/session_runner/runner.py:1459,1479`) are arguments to `evaluate_completion`, not the `AgentSession` constructor, and `create_local` handles a `stage_states` dict explicitly. Plan this as test-coverage hygiene plus an audit plus a design decision.
- **Do not restore #2949's kwarg mapping.** It is pinned by a test, for a reason recorded in that test module's docstring.
- Stay out of `pyproject.toml`, `scripts/update/`, and `agent/llm/` — those belong to #3001 and its Step 2 lane.

**Comment by tomcounsell** [comment]
Merged via PR #3145 (a8593a6fe). The unknown-kwargs rejection-decision writeup (keep popoto's constructor tolerance locally, pursue strictness upstream as opt-in Meta.strict_init if wanted) lives in that PR's body, section 3 — recorded here so the owner decision stays findable after closure.
