### PR TITLE
Fix apply_defaults embedding-provider import cycle (#3310)

### LINKED ISSUE #3310: apply_defaults silently drops the embedding provider when models.memory is imported before agent
**Plan:** https://github.com/tomcounsell/ai/blob/main/docs/plans/apply-defaults-embedding-provider-import-cycle.md

## Problem

`config/memory_defaults.py::apply_defaults()` configures the embedding provider inside a bare `except Exception: pass`. When `models.memory` is the first thing imported in a fresh process, the inner `from agent.embedding_provider import configure_embedding_provider` triggers `agent/__init__.py`, which eagerly imports `agent.agent_session_queue` and, through it, the half-initialized `models.memory`. The resulting `ImportError` is swallowed and `get_default_provider()` returns `None` for the life of the process.

Controlled comparison on main (`06ccc8d50`):

```
.venv/bin/python -c "import agent, models.memory; from popoto.fields.embedding_field import get_default_provider; print(get_default_provider())"
# -> <popoto.embeddings.openai.OpenAIProvider ...>

.venv/bin/python -c "import models.memory; from popoto.fields.embedding_field import get_default_provider; print(get_default_provider())"
# -> None
```

## Consequences

- Any entrypoint whose first import is `models.memory` ranks memory by BM25 only, with no query-embedding signal, and nothing logs it.
- Two workarounds already exist in the tree and neither fixes the cause: `scripts/spike/hybrid_retrieval_spikes.py` imports `agent` first and re-runs `configure_embedding_provider()`; `tools/memory_eval/provider_gate.py` refuses to rely on the implicit provider at all.
- Surfaced again by lane 4 (#3216, PR #3309): the evaluation arms inherit whichever provider the parent's import order happened to produce.

## Fix shape

Break the cycle rather than papering over it: `agent/embedding_provider.py` has no `agent` package dependencies (its imports are `logging`, `os`, `pathlib`), so `apply_defaults` can reach it without triggering `agent/__init__`, or the provider configuration can move out of `apply_defaults` into an explicit call at the process entrypoints. Either way, replace `except Exception: pass` with a logged failure so a missing provider is visible. Add a test that imports `models.memory` first in a subprocess and asserts a provider is configured.

Refs #3177 (found during lane 4, #3216).

---

## Triage 2026-09-15

**Status:** confirmed — reproduced on main (205344717). `python -c "import models.memory; from popoto.fields.embedding_field import get_default_provider; print(get_default_provider())"` prints `None`. Root cause traced with a loud (non-swallowing) `apply_defaults`: `models/memory.py:24` → `apply_defaults()` → `config/memory_defaults.py:249` imports `agent.embedding_provider` → triggers `agent/__init__.py` → `agent_session_queue` → `session_executor` → `agent/session_health.py:43` (`from models.memory import Memory`) → `ImportError: cannot import name 'Memory' from partially initialized module 'models.memory'`, caught and dropped by `config/memory_defaults.py:252` (`except Exception: pass`).

**Single-line hotfix:** No. Narrowing `except Exception` to `except ImportError` at `config/memory_defaults.py:252` changes nothing — the swallowed exception already is an `ImportError`. The real fix is breaking the cycle so `agent.session_health` doesn't reach back into `models.memory` at module-import time (or so `agent/__init__.py` doesn't eagerly pull in `agent_session_queue` → `session_executor` → `session_health` just to expose `configure_embedding_provider`), which is a multi-file change, not a one-liner.

**Reduce-complexity option:** Partially. The bare `try/except Exception: pass` around the embedding-provider call is exactly the "happy path + Sentry" anti-pattern — it converts a real import-order bug into permanent, silent, process-lifetime degradation with zero signal. Recommend removing that specific try/except (let a genuine `ImportError` here raise/log loudly to Sentry) while keeping the *intentional* degradation path inside `configure_embedding_provider()` itself (missing `OPENAI_API_KEY` is legitimately optional and already logs a warning). That alone doesn't fix the underlying circular import, but it converts a silent multi-day failure mode into an immediate, loud one.

---

## Recon Summary

**Confirmed:** 4 items — ready to include
- Cycle chain verified in tree: `models/memory.py:24` calls `apply_defaults()` at import time; `config/memory_defaults.py:249` does `from agent.embedding_provider import ...` which executes `agent/__init__.py` (eager `agent_session_queue` import); `agent/session_health.py:43` does `from models.memory import Memory`, closing the loop on a half-initialized module.
- Swallow site verified: `config/memory_defaults.py:252-253` is `except Exception: pass`, so the resulting `ImportError` leaves `get_default_provider()` returning `None` for process lifetime with zero log signal.
- Provider module is cycle-free: `agent/embedding_provider.py` imports only `logging`, `os`, `pathlib` (+ lazy `dotenv`/`popoto` inside the function), so reaching it without triggering `agent/__init__` is feasible.
- Workarounds exist and neither fixes the cause: `scripts/spike/hybrid_retrieval_spikes.py:20-25` imports `agent` first and re-runs `configure_embedding_provider()`; `tools/memory_eval/provider_gate.py` refuses to rely on the implicit provider.

**Revised:** 1 item — scope adjusted
- Fix shape narrowed to two candidate cuts (import-by-path reaching `agent.embedding_provider` without executing `agent/__init__`, vs explicit provider setup at process entrypoints), plus replacing the bare `except` with a logged failure; entrypoint inventory (`bridge/` startup vs worker/CLI paths that import `models.memory` first) happens during planning.

**Pre-requisites:** 0 items — none. No blocker; the triage reproduction on main stands.

**Dropped:** 1 item — removed from scope
- Narrowing `except Exception` to `except ImportError`: the swallowed exception already is an `ImportError`, so the narrowing changes nothing (per issue triage). Dropped as a fix; logging loudly is kept.

### PR DESCRIPTION
**Pull request by tomcounsell**
## Summary

Any process whose first import is `models.memory` silently ran with no embedding provider for its entire lifetime. `apply_defaults()` swallowed the ImportError raised when the `agent` package init reached back into the half-initialized `models.memory` module, so `get_default_provider()` returned None forever and retrieval degraded to BM25-only with no log signal.

## Changes

- `agent/session_health.py`: `from models.memory import Memory` moves from module top level to its single function-level use site in `cleanup_corrupted_agent_sessions`, cutting the back-edge of the cycle.
- `config/memory_defaults.py`: bare `except Exception: pass` becomes a logged warning naming `apply_defaults` and the embedding provider. Non-blocking intent preserved.
- `tests/unit/test_memory_import_order.py` (new): subprocess regression tests for both import orders plus a log-assertion test for genuine configuration failure. Written red-first: both failure modes reproduced before the fix.
- `docs/features/subconscious-memory.md`: import-order guarantee note.

## Testing

- [x] New regression test: 3 passed (was 2 failed before fix)
- [x] `tests/unit/test_memory_model.py` + `test_memory_distill_backfill.py`: 41 passed
- [x] Manual controlled comparison: both import orders now yield OpenAIProvider
- [x] Ruff check and format clean
- [x] `validate_docs_changed.py` passed, `validate_build.py` 2 PASS / 1 SKIP (test step timed out at 30s guard; full files run green directly)

## Documentation

- [x] Docs updated per plan requirements (existing feature doc, no new doc needed)

## Definition of Done

- [x] Built: Code implemented and working
- [x] Tested: All tests passing
- [x] Documented: Docs created/updated
- [x] Quality: Lint and format checks pass

Closes #3310

### CODE REVIEW

**Comment by tomcounsell** [comment]
## Review: Approved

Fix is narrow and correct. The cycle is cut at its single back-edge (`session_health` -> `models.memory` now lazy), the silent swallow is a logged warning, and both import orders were reproduced green in my own environment against worktree code. Red-state control on unfixed main prints `None`, so the new probes bite.

REVIEW_MODE: sequential lenses (Agent tool unavailable: not in tool list). This run applied both declared lenses (code-quality, risk) in sequence in one pass. Zero findings under either lens. Quorum note: 1 reporter covering a 2-judge roster, so this is a disclosed shortfall, not an independent consensus. Recommend a human second look at merge since multi-judge corroboration did not run.

## Rubric

- [x] **1. Plan vs. implementation match** — pass — *all 6 success criteria delivered in diff; relocation fallback correctly not taken (probes pass on lazy import alone)*
- [x] **2. New code quality** — pass — *lazy import carries an explanatory comment naming #3310; warning names apply_defaults and the provider; non-blocking intent preserved*
- [x] **3. Test coverage** — pass — *3 new regression tests; 41 memory model/backfill tests still pass; 61 session_health caller tests still pass*
- [x] **4. Regression risk to existing callers** — pass — *`cleanup_corrupted_agent_sessions` signature unchanged; callers covered by 61 passing tests; Risk 2 cleared (models/agent_session has no models.memory import)*
- [x] **5. Data integrity** — n/a — *no schema changes*
- [x] **6. Security** — pass — *no new sinks; logged exception text is ImportError/RuntimeError, no secrets*
- [x] **7. Documentation accuracy** — pass — *import-order guarantee note added to subconscious-memory.md; README index already lists the doc, no new doc created*
- [x] **8. PR body accuracy** — pass — *4 files match diff; "3 passed" and "41 passed" reproduced exactly; ruff clean reproduced; validate_docs_changed passes*
- [x] **9. Disclosed deferrals** — n/a — *no disclosure sections in PR body*
- [x] **10. Follow-up claims verified** — n/a — *no follow-up claims in PR body*

## Pre-Verdict Checklist

- **1. All plan acceptance/success criteria validated against diff** — PASS — *all 6 reproduced or verified (see Verification Results)*
- **2. No-Gos from plan — none violated** — PASS — *plan states "Nothing deferred"*
- **3. New `except Exception` blocks — each has logger/raise/swallow-ok** — PASS — *modified block logs via logger.warning, never blocks model definition*
- **4. New integration tests — exercise serialization boundary (not in-memory only)** — PASS — *subprocess probes use real process-global import state, stronger than in-memory*
- **5. Plan internal consistency — spike findings match task steps** — PASS — *lazy back-edge primary, apply_defaults path kept, relocation as fallback only*
- **6. No hardcoded secrets or debug artifacts** — PASS — *none*
- **7. New public APIs — docstrings present** — N/A — *test helpers are private; no new public APIs*
- **8. Breaking changes — migration path documented** — N/A — *no signature or behavior contract changes*
- **9. Tests added for new behavior** — PASS — *tests/unit/test_memory_import_order.py, 3 tests*
- **10. Tests cover the failure path (not just happy path)** — PASS — *log-assertion test patches configure to raise; keyless path skips gracefully by design*
- **11. UI changes (if any) — screenshot captured** — N/A — *no UI files in diff*
- **12. Docs updated for user-facing changes** — PASS — *subconscious-memory.md updated; validator passes*

### Verified
- [x] Code correctness
- [x] Test coverage
- [x] Security (no vulnerabilities found)
- [x] Plan requirements met

### Blockers
- None

### Tech Debt
- None

### Nits
- None

### Miscellaneous
- None

### Acknowledged Deferrals (verified)
- None

### Verification Results
- `import models.memory` first -> OpenAIProvider (reproduced, worktree code confirmed via `models.memory.__file__`)
- `import agent, models.memory` -> OpenAIProvider (reproduced)
- Red-state control on unfixed main (`PYTHONPATH=<main>`): `import models.memory` first -> `None`, confirming the probes detect the bug
- `tests/unit/test_memory_import_order.py`: 3 passed
- `tests/unit/test_memory_model.py` + `tests/unit/test_memory_distill_backfill.py`: 41 passed
- `tests/unit/test_session_health_phantom_guard.py` + `tests/unit/test_session_health_orphan_process_reap.py`: 61 passed
- `ruff check` + `ruff format --check` on changed files: clean (one pre-existing config notice: rule UP038 was removed upstream, ignoring it has no effect)
- `scripts/validate_docs_changed.py <plan>`: passed (notes README.md unindexed-change expectation; not applicable since no new doc was created and the index already lists subconscious-memory.md)
- Note: `scripts/pytest-clean.sh` refuses worktree runs (no worktree `.venv/bin/pytest`); tests above ran under the primary venv with `PYTHONPATH` pinned to the worktree so worktree code was exercised

### Screenshots
- None (no UI changes)

> Could not auto-sync "Update `docs/features/subconscious-memory.md` configuration notes with the import-order guarantee" — please review manually. (plan-checkbox writer MATCH_NOT_FOUND on the Documentation-section item; the doc update itself is verified in the diff. The 6 Success Criteria boxes were ticked and pushed in b33042f.)

**Comment by tomcounsell** [comment]
## Review: Approved

Re-verification at the new head `f5e8a71` after the DOCS commit. The delta since the prior approval (`b33042f`) is plan-doc only (status `docs_complete`, 2 Documentation checkboxes ticked); all code, tests, and feature docs are byte-identical. Every check below was re-run in my own environment against worktree code at the new head. Zero findings.

REVIEW_MODE: sequential lenses (Agent tool unavailable: not in tool list). This run applied both declared lenses (code-quality, risk) in sequence in one pass. Zero findings under either lens. Quorum note: 1 reporter covering a 2-judge roster, so this is a disclosed shortfall, not an independent consensus. Recommend a human second look at merge since multi-judge corroboration did not run.

## Rubric

- [x] **1. Plan vs. implementation match** — pass — *all 6 success criteria delivered; relocation fallback correctly not taken (probes pass on lazy import alone)*
- [x] **2. New code quality** — pass — *lazy import carries an explanatory comment naming #3310; warning names apply_defaults and the provider; non-blocking intent preserved*
- [x] **3. Test coverage** — pass — *3 new regression tests; 41 memory model/backfill tests still pass; 61 session_health caller tests still pass (all re-run at this head)*
- [x] **4. Regression risk to existing callers** — pass — *`cleanup_corrupted_agent_sessions` signature unchanged; callers covered by 61 passing tests; Risk 2 cleared (models/agent_session has no models.memory reference); no second module-level agent->models.memory edge (all remaining imports are function-level)*
- [x] **5. Data integrity** — n/a — *no schema changes*
- [x] **6. Security** — pass — *no new sinks; logged exception text is ImportError/RuntimeError, no secrets*
- [x] **7. Documentation accuracy** — pass — *import-order guarantee note in subconscious-memory.md; README index already lists the doc, no new doc created*
- [x] **8. PR body accuracy** — pass — *code/feature-doc/test claims reproduced exactly ("3 passed", "41 passed", ruff clean, validate_docs_changed pass); validate_build 2 PASS / 1 SKIP taken as disclosed (full test files run green directly in this review)*
- [x] **9. Disclosed deferrals** — n/a — *no disclosure sections in PR body*
- [x] **10. Follow-up claims verified** — n/a — *no follow-up claims in PR body*

## Pre-Verdict Checklist

- **1. All plan acceptance/success criteria validated against diff** — PASS — *all 6 reproduced or verified (see Verification Results)*
- **2. No-Gos from plan — none violated** — PASS — *plan states "Nothing deferred"*
- **3. New `except Exception` blocks — each has logger/raise/swallow-ok** — PASS — *modified block logs via logger.warning, never blocks model definition*
- **4. New integration tests — exercise serialization boundary (not in-memory only)** — PASS — *subprocess probes use real process-global import state, stronger than in-memory*
- **5. Plan internal consistency — spike findings match task steps** — PASS — *lazy back-edge primary, apply_defaults path kept, relocation as fallback only*
- **6. No hardcoded secrets or debug artifacts** — PASS — *none*
- **7. New public APIs — docstrings present** — N/A — *test helpers are private; no new public APIs*
- **8. Breaking changes — migration path documented** — N/A — *no signature or behavior contract changes*
- **9. Tests added for new behavior** — PASS — *tests/unit/test_memory_import_order.py, 3 tests*
- **10. Tests cover the failure path (not just happy path)** — PASS — *log-assertion test patches configure to raise; keyless path skips gracefully by design*
- **11. UI changes (if any) — screenshot captured** — N/A — *no UI files in diff*
- **12. Docs updated for user-facing changes** — PASS — *subconscious-memory.md updated; validator passes*

### Verified
- [x] Code correctness
- [x] Test coverage
- [x] Security (no vulnerabilities found)
- [x] Plan requirements met

### Blockers
- None

### Tech Debt
- None

### Nits
- None

### Miscellaneous
- None

### Acknowledged Deferrals (verified)
- None

### Review Delta (vs prior review on HEAD b33042f)
- **Unchanged**: all prior findings (zero) carried forward; code, tests, and feature docs byte-identical across the docs commit
- **New**: plan-doc status flip (`Planning` -> `docs_complete`) and 2 Documentation checkbox ticks — the DOCS stage output this re-verification was asked to cover
- **Resolved**: nothing (there was nothing to resolve)

### Verification Results (re-run at f5e8a71, worktree code)
- `import models.memory` first -> OpenAIProvider (reproduced, `models.memory.__file__` confirmed under the worktree)
- `import agent, models.memory` -> OpenAIProvider (reproduced)
- Red-state control on unfixed main checkout (neutral cwd, `PYTHONPATH=<main>`): `import models.memory` first -> `None`, confirming the probes bite
- `tests/unit/test_memory_import_order.py` + `test_memory_model.py` + `test_memory_distill_backfill.py`: 44 passed
- `tests/unit/test_session_health_phantom_guard.py` + `test_session_health_orphan_process_reap.py`: 61 passed
- `ruff check` + `ruff format --check` on the 3 changed Python files: clean (one pre-existing config notice: rule UP038 was removed upstream, ignoring it has no effect)
- `scripts/validate_docs_changed.py <plan>`: passed (README.md unindexed-change note is expected: no new doc was created and the index already lists subconscious-memory.md)
- Note: `scripts/pytest-clean.sh` refuses worktree runs (no worktree `.venv/bin/pytest`); tests above ran under the primary venv with `PYTHONPATH` pinned to the worktree so worktree code was exercised

### Screenshots
- None (no UI changes)
